{
  "cna_info": {
    "cna": "Xiaomi",
    "total_cves": 8,
    "total_cves_scored": 8,
    "average_eas_score": 64.0,
    "overall_average_score": 64.0,
    "average_foundational_completeness": 30.0,
    "average_root_cause_analysis": 20.0,
    "average_severity_context": 10.0,
    "average_actionable_intelligence": 4.0,
    "average_data_format_precision": 0.0,
    "percentile": 68.2
  },
  "recent_cves": [
    {
      "cveId": "CVE-2024-45354",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45355",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45356",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45353",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45351",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45347",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45352",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    },
    {
      "cveId": "CVE-2024-45361",
      "assigningCna": "Xiaomi",
      "totalEasScore": 64,
      "scoreBreakdown": {
        "foundationalCompleteness": 30,
        "rootCauseAnalysis": 20,
        "severityAndImpactContext": 10,
        "actionableIntelligence": 4,
        "dataFormatAndPrecision": 0
      }
    }
  ],
  "total_cves": 8
}